spring:
  application:
    name: pw-paratransit
  security:
    oauth2:
      client:
        provider:
          casedata:
            token-uri: ${config.casedata.token-uri}
          templating:
            token-uri: ${config.templating.token-uri}
          messaging:
            token-uri: ${config.messaging.token-uri}
          citizen:
            token-uri: ${config.citizen.token-uri}
          partyassets:
            token-uri: ${config.partyassets.token-uri}
        registration:
          casedata:
            authorization-grant-type: client_credentials
            provider: casedata
            client-id: ${config.casedata.client-id}
            client-secret: ${config.casedata.client-secret}
          templating:
            authorization-grant-type: client_credentials
            provider: templating
            client-id: ${config.templating.client-id}
            client-secret: ${config.templating.client-secret}
          messaging:
            authorization-grant-type: client_credentials
            provider: messaging
            client-id: ${config.messaging.client-id}
            client-secret: ${config.messaging.client-secret}
          citizen:
            authorization-grant-type: client_credentials
            provider: citizen
            client-id: ${config.citizen.client-id}
            client-secret: ${config.citizen.client-secret}
          partyassets:
            authorization-grant-type: client_credentials
            provider: partyassets
            client-id: ${config.partyassets.client-id}
            client-secret: ${config.partyassets.client-secret}
#----------------------------------------
# Open API
#----------------------------------------
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'

#----------------------------------------
# Camunda
#----------------------------------------
camunda:
  bpm:
    client:
      base-url: ${config.camunda.base-url}
      backoff:
        initTime: 500
        factor: 2
        maxTime: 15000
    deployment:
      processes:
        - name: Paratransit process
          tenant: PARATRANSIT
          bpmnResourcePattern: classpath*:processmodels/*.bpmn
          dmnResourcePattern: classpath*:processmodels/*.dmn
          formResourcePattern: classpath*:processmodels/*.form
  worker:
    max:
      retries: 3
    retry:
      timeout: 10

#----------------------------------------
# Camunda integration settings
#----------------------------------------
# Rest client
integration:
  camunda:
    connectTimeout: 5
    readTimeout: 20
    url: ${config.camunda.base-url}
  casedata:
    connectTimeout: 5
    readTimeout: 20
    url: ${config.casedata.base-url}
  templating:
    connectTimeout: 5
    readTimeout: 20
    url: ${config.templating.base-url}
  citizen:
    connectTimeout: 5
    readTimeout: 20
    url: ${config.citizen.base-url}
  messaging:
    connectTimeout: 5
    readTimeout: 20
    url: ${config.messaging.base-url}
  partyassets:
    url: ${config.partyassets.base-url}
    connectTimeout: 5
    readTimeout: 20

#----------------------------------------
# Circuit breakers
#----------------------------------------
resilience4j.circuitbreaker:
  instances:
    camunda:
      ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
    casedata:
      ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
    templating:
      ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
    messaging:
      ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
    citizen:
      ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
    partyassets:
      ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem