#========================================
# Integration test specific settings
#========================================
#----------------------------------------
# Spring settings
#----------------------------------------
spring:
  application:
    name: pw-paratransit-it
  main:
    banner-mode: "off"
#----------------------------------------
# Open API
#----------------------------------------
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
#----------------------------------------
# Camunda integration settings
#----------------------------------------
# Rest client
config:
  camunda:
    base-url: http://localhost:${wiremock.server.port}/api-camunda/engine-rest
  citizen:
    base-url: http://localhost:${wiremock.server.port}/api-citizen
    token-uri: ${config.common.token-uri}
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}
  messaging:
    base-url: http://localhost:${wiremock.server.port}/api-messaging
    token-uri: ${config.common.token-uri}
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}
  partyassets:
    base-url: http://localhost:${wiremock.server.port}/api-party-assets
    token-uri: ${config.common.token-uri}
    client-id: ${config.common.client-id}
    client-secret: ${config.common.client-secret}