#========================================
# Integration test specific settings
#========================================
#----------------------------------------
# Spring settings
#----------------------------------------
spring:
  application:
    name: pw-paratransit-it
  main:
    banner-mode: "off"
#----------------------------------------
# Open API
#----------------------------------------
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
#----------------------------------------
# Camunda integration settings
#----------------------------------------
# Rest client
config:
  camunda:
    base-url: http://localhost:${wiremock.server.port}/api-camunda/engine-rest
